sudo: false
language: node_js
node_js:
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
after_success:
  - eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-deploy.bash)"
# configuration commands
# travis env set SURGE_LOGIN "$SURGE_LOGIN" --public
# travis env set SURGE_TOKEN "$SURGE_TOKEN"
# travis encrypt "mangrovefriends:$SLACK_TRAVIS_TOKEN#updates" --add notifications.slack⏎