# 2017 May 25
# https://docpad.org/docs/deploy
# https://github.com/balupton/awesome-travis
sudo: false
language: node_js
node_js:
  - "8"     # stable
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.yarn-cache"
install:
  - npm install --only=prod
  - npm install --only=dev
after_success:
  - eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/deploy-custom.bash)"
